@KofCWSC.API_HostAddress = https://localhost:7078

GET {{KofCWSC.API_HostAddress}}/api/TblMasMember/{id}?memberid=19183

###

GET {{KofCWSC.API_HostAddress}}/api/tblmasmembers/0

###

PUT {{KofCWSC.API_HostAddress}}/UpdMember/0
Content-Type: application/json

{
  //TblMasMember
}

###

GET {{KofCWSC.API_HostAddress}}/GetMembers/ByLastName/philomeno

###

GET {{KofCWSC.API_HostAddress}}/VerifyKofCID/3970136

###

GET {{KofCWSC.API_HostAddress}}/users/VerifyKofCID?KofCMemberID=string

###
