@KofCWSC.API_HostAddress = https://localhost:7078

GET {{KofCWSC.API_HostAddress}}/api/TblMasMember/{id}?memberid=19183

###

GET {{KofCWSC.API_HostAddress}}/api/tblmasmembers/0

###

PUT {{KofCWSC.API_HostAddress}}/UpdMember/0
Content-Type: application/json

{
  //TblMasMember
}

###

GET {{KofCWSC.API_HostAddress}}/GetMembers/ByLastName/philomeno

###

GET {{KofCWSC.API_HostAddress}}/VerifyKofCID/3970136

###

GET {{KofCWSC.API_HostAddress}}/users/VerifyKofCID?KofCMemberID=string

###

GET {{KofCWSC.API_HostAddress}}/api/TblMasPSOs

###
GET {{KofCWSC.API_HostAddress}}/api/TblMasPSOs/{id}

###
POST {{KofCWSC.API_HostAddress}}/api/TblMasPSOs
Content-Type: application/json

{
  "Year": 2024,
  "StateDeputy": "John Doe",
  "StateSecretary": "James Smith",
  "StateTreasurer": "Jim Brown",
  "StateAdvocate": "Jack White",
  "StateWarden": "Bill Green"
}

###

PUT {{KofCWSC.API_HostAddress}}/api/TblMasPSOs/{id}
Content-Type: application/json

{
  "Id": 1,
  "Year": 2024,
  "StateDeputy": "John Doe",
  "StateSecretary": "James Smith",
  "StateTreasurer": "Jim Brown",
  "StateAdvocate": "Jack White",
  "StateWarden": "Bill Green"
}

###

DELETE {{KofCWSC.API_HostAddress}}/api/TblMasPSOs/{id}

###
GET {{KofCWSC.API_HostAddress}}/api/TblValAssys

###

GET {{KofCWSC.API_HostAddress}}/api/TblValAssys/{id}

###

POST {{KofCWSC.API_HostAddress}}/api/TblValAssys
Content-Type: application/json

{
  "ANumber": 123,
  "ALocation": "Some Location",
  "AName": "Some Name",
  "AddInfo1": "Additional Info 1",
  "AddInfo2": "Additional Info 2",
  "AddInfo3": "Additional Info 3",
  "WebSiteUrl": "https://example.com",
  "MasterLoc": "Some Master Location"
}

###

PUT {{KofCWSC.API_HostAddress}}/api/TblValAssys/{id}
Content-Type: application/json

{
  "ANumber": 123,
  "ALocation": "Updated Location",
  "AName": "Updated Name",
  "AddInfo1": "Updated Info 1",
  "AddInfo2": "Updated Info 2",
  "AddInfo3": "Updated Info 3",
  "WebSiteUrl": "https://example.com",
  "MasterLoc": "Updated Master Location"
}

###

DELETE {{KofCWSC.API_HostAddress}}/api/TblValAssys/{id}

###

GET {{KofCWSC.API_HostAddress}}/api/TblValCouncils

###

GET {{KofCWSC.API_HostAddress}}/api/TblValCouncils/{id}

###
POST {{KofCWSC.API_HostAddress}} /api/TblValCouncils
Content-Type: application/json

{
  "CNumber": 1010,
  "CLocation": "New City",
  "CName": "New Council Name",
  "District": 5,
  "AddInfo1": "Additional Info 1",
  "AddInfo2": "Additional Info 2",
  "AddInfo3": "Additional Info 3",
  "LiabIns": true,
  "DioceseId": "Diocese 100",
  "Chartered": "2023-01-01T00:00:00",
  "WebSiteUrl": "http://www.newcouncilwebsite.com",
  "BulletinUrl": "http://www.newcouncilbulletin.com",
  "Arbalance": 5000.00,
  "Status": "Active"
}

###
PUT {{KofCWSC.API_HostAddress}} /api/TblValCouncils/{id}
Content-Type: application/json

{
  "CNumber": 1010,
  "CLocation": "Updated City",
  "CName": "Updated Council Name",
  "District": 6,
  "AddInfo1": "Updated Additional Info 1",
  "AddInfo2": "Updated Additional Info 2",
  "AddInfo3": "Updated Additional Info 3",
  "LiabIns": false,
  "DioceseId": "Diocese 200",
  "Chartered": "2023-01-01T00:00:00",
  "WebSiteUrl": "http://www.updatedcouncilwebsite.com",
  "BulletinUrl": "http://www.updatedcouncilbulletin.com",
  "Arbalance": 3000.00,
  "Status": "Inactive"
}
###

DELETE {{KofCWSC.API_HostAddress}}/api/TblValCouncils/{id}

### Get Bulletins
GET {{host}}/api/SP/GetBulletins
Accept: application/json

### Get Email Alias
GET {{host}}/api/SP/GetEmailAlias
Accept: application/json

### Get Chairmen
GET {{host}}/api/SP/GetChairmen
Accept: application/json

### Get Chairman Info Block by ID
GET {{host}}/api/SP/GetChairmanInfoBlock/{id}
Accept: application/json

### Get DDs
GET {{host}}/api/SP/GetDDs
Accept: application/json

### Get Fourth Degree Officers
GET {{host}}/api/SP/FourthDegreeOfficers
Accept: application/json



### Get All TblValOffices
GET {{host}}/api/TblValOffices
Accept: application/json

### Get TblValOffice by ID
GET {{host}}/api/TblValOffices/{id}
Accept: application/json

### Create New TblValOffice
POST {{host}}/api/TblValOffices
Content-Type: application/json
Accept: application/json
{
  "OfficeDescription": "New Office",
  "DirSortOrder": 1,
  "AltDescription": "Alternate Description",
  "EmailAlias": "email@example.com",
  "UseAsFormalTitle": true,
  "WebPageTagLine": "Web Page Tag Line",
  "SupremeUrl": "http://example.com"
}

### Update TblValOffice
PUT {{host}}/api/TblValOffices/{id}
Content-Type: application/json
Accept: application/json
{
  "OfficeId": 1,
  "OfficeDescription": "Updated Office",
  "DirSortOrder": 2,
  "AltDescription": "Updated Alternate Description",
  "EmailAlias": "updatedemail@example.com",
  "UseAsFormalTitle": false,
  "WebPageTagLine": "Updated Web Page Tag Line",
  "SupremeUrl": "http://example.com/updated"
}

### Delete TblValOffice
DELETE {{host}}/api/TblValOffices/{id}
Accept: application/json

### Get All Offices
GET {{host}}/api/Offices
Accept: application/json

### Get Office by ID
GET {{host}}/api/Offices/{id}
Accept: application/json

### Create New Office
POST {{host}}/api/Offices
Content-Type: application/json
Accept: application/json
{
  "OfficeDescription": "New Office",
  "DirSortOrder": 1,
  "AltDescription": "Alternate Description",
  "EmailAlias": "email@example.com",
  "UseAsFormalTitle": true,
  "WebPageTagLine": "Web Page Tag Line",
  "SupremeUrl": "http://example.com"
}

### Update Office
PUT {{host}}/api/Offices/{id}
Content-Type: application/json
Accept: application/json
{
  "OfficeId": 1,
  "OfficeDescription": "Updated Office",
  "DirSortOrder": 2,
  "AltDescription": "Updated Alternate Description",
  "EmailAlias": "updatedemail@example.com",
  "UseAsFormalTitle": false,
  "WebPageTagLine": "Updated Web Page Tag Line",
  "SupremeUrl": "http://example.com/updated"
}

### Delete Office
DELETE {{host}}/api/Offices/{id}
Accept: application/json

### Get All Awards
GET {{host}}/api/MasAwards
Accept: application/json

### Get Award Details by ID
GET {{host}}/api/MasAwards/{id}
Accept: application/json

### Create New Award
POST {{host}}/api/MasAwards
Content-Type: application/json
Accept: application/json
{
  "AwardName": "Best Member",
  "AwardDescription": "Award for the best member of the year.",
  "AwardDueDate": "2023-12-31T00:00:00Z",
  "LinkToTheAwardForm": "http://example.com/form",
  "AwardSubmissionEmailAddress": "submit@example.com"
}

### Update Award
PUT {{host}}/api/MasAwards/{id}
Content-Type: application/json
Accept: application/json
{
  "Id": 1,
  "AwardName": "Best Member Updated",
  "AwardDescription": "Updated description for the best member of the year.",
  "AwardDueDate": "2024-12-31T00:00:00Z",
  "LinkToTheAwardForm": "http://example.com/updated_form",
  "AwardSubmissionEmailAddress": "updated_submit@example.com"
}

### Delete Award
DELETE {{host}}/api/MasAwards/{id}
Accept: application/json

### Get Home Page Data
GET {{host}}/api/Home
Accept: application/json

### Get Privacy Information
GET {{host}}/api/Home/Privacy
Accept: application/json

### Health Check
GET {{host}}/api/Home/HealthCheck
Accept: application/json

### Simulate an Error
GET {{host}}/api/Home/Error
Accept: application/json

### Get All WebSelfPublishes
GET {{host}}/api/SelfPublish
Accept: application/json

### Get WebSelfPublish by URL
GET {{host}}/api/SelfPublish/Details/{id}
Accept: application/json

### Display WebSelfPublish Data
GET {{host}}/api/SelfPublish/Display/{id}
Accept: application/json

### Create New WebSelfPublish
POST {{host}}/api/SelfPublish/Create
Content-Type: application/json
Accept: application/json
{
  "Url": "http://example.com",
  "Data": "Some data"
}

### Update WebSelfPublish
PUT {{host}}/api/SelfPublish/Edit/{id}
Content-Type: application/json
Accept: application/json
{
  "Url": "http://example.com",
  "Data": "Updated data",
  "OID": 1
}

### Delete WebSelfPublish
DELETE {{host}}/api/SelfPublish/Delete/{id}
Accept: application/json